# Generated by Django 2.0.7 on 2018-07-13 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awsdeploytest', '0001_initial'),
        ('awsdeploytest_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tenant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='awsdeploytest.Client'),
            preserve_default=False,
        ),
    ]
